version: '3'

services:
  # app:
  #   image: docker-gamer-gear-dev
  #   build: .
  #   ports: 
  #     - 3000:3000
  #   volumes:
  #   - ./pages:/app/pages
  #   - ./public:/app/public
  #   - ./styles:/app/styles

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
          PRISMA_CONFIG: |
            port: 4466
            managementApiSecret: __YOUR_MANAGEMENT_API_SECRET__
            databases:
              default:
                connector: mongo
                uri: $DATABASE_URL
    
  mongo-db:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    ports:
      - '27017:27017'
    volumes:
      - mongo:/var/lib/mongo
volumes: 
  mongo: